### ISSUE TITLE
iOS 16 / macOS Ventura refresh

### ISSUE THREAD

**Issue by Obnoxieux** [Obnoxieux/Berlin-Skylarks#55]
- [x] iPad task bar
- [x] SwiftUI share sheet
- [x] adjust iPad navigation to have better column width
- [x] use SwiftUI charts instead of self-built ones
